<?php
/**
* Template Name: FA5 Light
*
* @package understrap
*/

get_header(); ?>

<div id="content" class="site-content container"><!-- closed in footer.php -->

	<div class="row">
		<div class="col-12"> <!-- Default Page is Full-Width -->
			<div id="primary" class="content-area">
				<main id="main" class="site-main">
					<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
						<header class="entry-header">
							<?php the_title( '<h1 class="entry-title">', '</h1>' ); ?>
						</header><!-- .entry-header -->
						<div class="entry-content card">

							<div class="row">

							<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-address-book fa-3x"></i><span class="d-block">address-book</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-address-card fa-3x"></i><span class="d-block">address-card</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-adjust fa-3x"></i><span class="d-block">adjust</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-alarm-clock fa-3x"></i><span class="d-block">alarm-clock</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-align-center fa-3x"></i><span class="d-block">align-center</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-align-justify fa-3x"></i><span class="d-block">align-justify</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-align-left fa-3x"></i><span class="d-block">align-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-align-right fa-3x"></i><span class="d-block">align-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ambulance fa-3x"></i><span class="d-block">ambulance</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-american-sign-language-interpreting fa-3x"></i><span class="d-block">american-sign-language-interpreting</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-anchor fa-3x"></i><span class="d-block">anchor</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-double-down fa-3x"></i><span class="d-block">angle-double-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-double-left fa-3x"></i><span class="d-block">angle-double-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-double-right fa-3x"></i><span class="d-block">angle-double-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-double-up fa-3x"></i><span class="d-block">angle-double-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-down fa-3x"></i><span class="d-block">angle-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-left fa-3x"></i><span class="d-block">angle-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-right fa-3x"></i><span class="d-block">angle-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-angle-up fa-3x"></i><span class="d-block">angle-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-archive fa-3x"></i><span class="d-block">archive</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-circle-down fa-3x"></i><span class="d-block">arrow-alt-circle-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-circle-left fa-3x"></i><span class="d-block">arrow-alt-circle-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-circle-right fa-3x"></i><span class="d-block">arrow-alt-circle-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-circle-up fa-3x"></i><span class="d-block">arrow-alt-circle-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-down fa-3x"></i><span class="d-block">arrow-alt-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-from-bottom fa-3x"></i><span class="d-block">arrow-alt-from-bottom</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-from-left fa-3x"></i><span class="d-block">arrow-alt-from-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-from-right fa-3x"></i><span class="d-block">arrow-alt-from-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-from-top fa-3x"></i><span class="d-block">arrow-alt-from-top</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-left fa-3x"></i><span class="d-block">arrow-alt-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-right fa-3x"></i><span class="d-block">arrow-alt-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-square-down fa-3x"></i><span class="d-block">arrow-alt-square-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-square-left fa-3x"></i><span class="d-block">arrow-alt-square-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-square-right fa-3x"></i><span class="d-block">arrow-alt-square-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-square-up fa-3x"></i><span class="d-block">arrow-alt-square-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-to-bottom fa-3x"></i><span class="d-block">arrow-alt-to-bottom</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-to-left fa-3x"></i><span class="d-block">arrow-alt-to-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-to-right fa-3x"></i><span class="d-block">arrow-alt-to-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-to-top fa-3x"></i><span class="d-block">arrow-alt-to-top</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-alt-up fa-3x"></i><span class="d-block">arrow-alt-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-circle-down fa-3x"></i><span class="d-block">arrow-circle-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-circle-left fa-3x"></i><span class="d-block">arrow-circle-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-circle-right fa-3x"></i><span class="d-block">arrow-circle-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-circle-up fa-3x"></i><span class="d-block">arrow-circle-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-down fa-3x"></i><span class="d-block">arrow-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-from-bottom fa-3x"></i><span class="d-block">arrow-from-bottom</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-from-left fa-3x"></i><span class="d-block">arrow-from-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-from-right fa-3x"></i><span class="d-block">arrow-from-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-from-top fa-3x"></i><span class="d-block">arrow-from-top</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-left fa-3x"></i><span class="d-block">arrow-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-right fa-3x"></i><span class="d-block">arrow-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-square-down fa-3x"></i><span class="d-block">arrow-square-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-square-left fa-3x"></i><span class="d-block">arrow-square-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-square-right fa-3x"></i><span class="d-block">arrow-square-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-square-up fa-3x"></i><span class="d-block">arrow-square-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-to-bottom fa-3x"></i><span class="d-block">arrow-to-bottom</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-to-left fa-3x"></i><span class="d-block">arrow-to-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-to-right fa-3x"></i><span class="d-block">arrow-to-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-to-top fa-3x"></i><span class="d-block">arrow-to-top</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrow-up fa-3x"></i><span class="d-block">arrow-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrows fa-3x"></i><span class="d-block">arrows</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrows-alt fa-3x"></i><span class="d-block">arrows-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrows-alt-h fa-3x"></i><span class="d-block">arrows-alt-h</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrows-alt-v fa-3x"></i><span class="d-block">arrows-alt-v</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrows-h fa-3x"></i><span class="d-block">arrows-h</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-arrows-v fa-3x"></i><span class="d-block">arrows-v</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-assistive-listening-systems fa-3x"></i><span class="d-block">assistive-listening-systems</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-asterisk fa-3x"></i><span class="d-block">asterisk</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-at fa-3x"></i><span class="d-block">at</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-audio-description fa-3x"></i><span class="d-block">audio-description</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-backward fa-3x"></i><span class="d-block">backward</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-badge fa-3x"></i><span class="d-block">badge</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-badge-check fa-3x"></i><span class="d-block">badge-check</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-balance-scale fa-3x"></i><span class="d-block">balance-scale</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ban fa-3x"></i><span class="d-block">ban</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-barcode fa-3x"></i><span class="d-block">barcode</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bars fa-3x"></i><span class="d-block">bars</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bath fa-3x"></i><span class="d-block">bath</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-battery-bolt fa-3x"></i><span class="d-block">battery-bolt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-battery-empty fa-3x"></i><span class="d-block">battery-empty</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-battery-full fa-3x"></i><span class="d-block">battery-full</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-battery-half fa-3x"></i><span class="d-block">battery-half</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-battery-quarter fa-3x"></i><span class="d-block">battery-quarter</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-battery-slash fa-3x"></i><span class="d-block">battery-slash</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-battery-three-quarters fa-3x"></i><span class="d-block">battery-three-quarters</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bed fa-3x"></i><span class="d-block">bed</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-beer fa-3x"></i><span class="d-block">beer</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bell fa-3x"></i><span class="d-block">bell</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bell-slash fa-3x"></i><span class="d-block">bell-slash</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bicycle fa-3x"></i><span class="d-block">bicycle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-binoculars fa-3x"></i><span class="d-block">binoculars</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-birthday-cake fa-3x"></i><span class="d-block">birthday-cake</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-blind fa-3x"></i><span class="d-block">blind</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bold fa-3x"></i><span class="d-block">bold</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bolt fa-3x"></i><span class="d-block">bolt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bomb fa-3x"></i><span class="d-block">bomb</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-book fa-3x"></i><span class="d-block">book</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bookmark fa-3x"></i><span class="d-block">bookmark</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-braille fa-3x"></i><span class="d-block">braille</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-briefcase fa-3x"></i><span class="d-block">briefcase</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-browser fa-3x"></i><span class="d-block">browser</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bug fa-3x"></i><span class="d-block">bug</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-building fa-3x"></i><span class="d-block">building</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bullhorn fa-3x"></i><span class="d-block">bullhorn</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bullseye fa-3x"></i><span class="d-block">bullseye</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-bus fa-3x"></i><span class="d-block">bus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calculator fa-3x"></i><span class="d-block">calculator</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar fa-3x"></i><span class="d-block">calendar</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar-alt fa-3x"></i><span class="d-block">calendar-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar-check fa-3x"></i><span class="d-block">calendar-check</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar-edit fa-3x"></i><span class="d-block">calendar-edit</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar-exclamation fa-3x"></i><span class="d-block">calendar-exclamation</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar-minus fa-3x"></i><span class="d-block">calendar-minus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar-plus fa-3x"></i><span class="d-block">calendar-plus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-calendar-times fa-3x"></i><span class="d-block">calendar-times</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-camera fa-3x"></i><span class="d-block">camera</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-camera-alt fa-3x"></i><span class="d-block">camera-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-camera-retro fa-3x"></i><span class="d-block">camera-retro</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-car fa-3x"></i><span class="d-block">car</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-circle-down fa-3x"></i><span class="d-block">caret-circle-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-circle-left fa-3x"></i><span class="d-block">caret-circle-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-circle-right fa-3x"></i><span class="d-block">caret-circle-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-circle-up fa-3x"></i><span class="d-block">caret-circle-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-down fa-3x"></i><span class="d-block">caret-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-left fa-3x"></i><span class="d-block">caret-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-right fa-3x"></i><span class="d-block">caret-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-square-down fa-3x"></i><span class="d-block">caret-square-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-square-left fa-3x"></i><span class="d-block">caret-square-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-square-right fa-3x"></i><span class="d-block">caret-square-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-square-up fa-3x"></i><span class="d-block">caret-square-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-caret-up fa-3x"></i><span class="d-block">caret-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cart-arrow-down fa-3x"></i><span class="d-block">cart-arrow-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cart-plus fa-3x"></i><span class="d-block">cart-plus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-certificate fa-3x"></i><span class="d-block">certificate</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chart-area fa-3x"></i><span class="d-block">chart-area</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chart-bar fa-3x"></i><span class="d-block">chart-bar</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chart-line fa-3x"></i><span class="d-block">chart-line</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chart-pie fa-3x"></i><span class="d-block">chart-pie</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-check fa-3x"></i><span class="d-block">check</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-check-circle fa-3x"></i><span class="d-block">check-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-check-square fa-3x"></i><span class="d-block">check-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-circle-down fa-3x"></i><span class="d-block">chevron-circle-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-circle-left fa-3x"></i><span class="d-block">chevron-circle-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-circle-right fa-3x"></i><span class="d-block">chevron-circle-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-circle-up fa-3x"></i><span class="d-block">chevron-circle-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-double-down fa-3x"></i><span class="d-block">chevron-double-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-double-left fa-3x"></i><span class="d-block">chevron-double-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-double-right fa-3x"></i><span class="d-block">chevron-double-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-double-up fa-3x"></i><span class="d-block">chevron-double-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-down fa-3x"></i><span class="d-block">chevron-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-left fa-3x"></i><span class="d-block">chevron-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-right fa-3x"></i><span class="d-block">chevron-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-square-down fa-3x"></i><span class="d-block">chevron-square-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-square-left fa-3x"></i><span class="d-block">chevron-square-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-square-right fa-3x"></i><span class="d-block">chevron-square-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-square-up fa-3x"></i><span class="d-block">chevron-square-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-chevron-up fa-3x"></i><span class="d-block">chevron-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-child fa-3x"></i><span class="d-block">child</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-circle fa-3x"></i><span class="d-block">circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-circle-notch fa-3x"></i><span class="d-block">circle-notch</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-clipboard fa-3x"></i><span class="d-block">clipboard</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-clock fa-3x"></i><span class="d-block">clock</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-clone fa-3x"></i><span class="d-block">clone</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-closed-captioning fa-3x"></i><span class="d-block">closed-captioning</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cloud fa-3x"></i><span class="d-block">cloud</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cloud-download fa-3x"></i><span class="d-block">cloud-download</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cloud-download-alt fa-3x"></i><span class="d-block">cloud-download-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cloud-upload fa-3x"></i><span class="d-block">cloud-upload</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cloud-upload-alt fa-3x"></i><span class="d-block">cloud-upload-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-club fa-3x"></i><span class="d-block">club</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-code fa-3x"></i><span class="d-block">code</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-code-branch fa-3x"></i><span class="d-block">code-branch</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-code-commit fa-3x"></i><span class="d-block">code-commit</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-code-merge fa-3x"></i><span class="d-block">code-merge</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-coffee fa-3x"></i><span class="d-block">coffee</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cog fa-3x"></i><span class="d-block">cog</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cogs fa-3x"></i><span class="d-block">cogs</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-columns fa-3x"></i><span class="d-block">columns</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-comment fa-3x"></i><span class="d-block">comment</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-comment-alt fa-3x"></i><span class="d-block">comment-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-comments fa-3x"></i><span class="d-block">comments</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-compass fa-3x"></i><span class="d-block">compass</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-compress fa-3x"></i><span class="d-block">compress</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-compress-wide fa-3x"></i><span class="d-block">compress-wide</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-copy fa-3x"></i><span class="d-block">copy</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-copyright fa-3x"></i><span class="d-block">copyright</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-credit-card fa-3x"></i><span class="d-block">credit-card</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-credit-card-blank fa-3x"></i><span class="d-block">credit-card-blank</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-credit-card-front fa-3x"></i><span class="d-block">credit-card-front</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-crop fa-3x"></i><span class="d-block">crop</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-crosshairs fa-3x"></i><span class="d-block">crosshairs</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cube fa-3x"></i><span class="d-block">cube</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cubes fa-3x"></i><span class="d-block">cubes</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-cut fa-3x"></i><span class="d-block">cut</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-database fa-3x"></i><span class="d-block">database</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-deaf fa-3x"></i><span class="d-block">deaf</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-desktop fa-3x"></i><span class="d-block">desktop</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-desktop-alt fa-3x"></i><span class="d-block">desktop-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-diamond fa-3x"></i><span class="d-block">diamond</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-dollar-sign fa-3x"></i><span class="d-block">dollar-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-dot-circle fa-3x"></i><span class="d-block">dot-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-download fa-3x"></i><span class="d-block">download</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-edit fa-3x"></i><span class="d-block">edit</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-eject fa-3x"></i><span class="d-block">eject</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ellipsis-h fa-3x"></i><span class="d-block">ellipsis-h</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ellipsis-h-alt fa-3x"></i><span class="d-block">ellipsis-h-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ellipsis-v fa-3x"></i><span class="d-block">ellipsis-v</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ellipsis-v-alt fa-3x"></i><span class="d-block">ellipsis-v-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-envelope fa-3x"></i><span class="d-block">envelope</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-envelope-open fa-3x"></i><span class="d-block">envelope-open</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-envelope-square fa-3x"></i><span class="d-block">envelope-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-eraser fa-3x"></i><span class="d-block">eraser</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-euro-sign fa-3x"></i><span class="d-block">euro-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-exchange fa-3x"></i><span class="d-block">exchange</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-exchange-alt fa-3x"></i><span class="d-block">exchange-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-exclamation fa-3x"></i><span class="d-block">exclamation</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-exclamation-circle fa-3x"></i><span class="d-block">exclamation-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-exclamation-square fa-3x"></i><span class="d-block">exclamation-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-exclamation-triangle fa-3x"></i><span class="d-block">exclamation-triangle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-expand fa-3x"></i><span class="d-block">expand</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-expand-arrows fa-3x"></i><span class="d-block">expand-arrows</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-expand-arrows-alt fa-3x"></i><span class="d-block">expand-arrows-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-expand-wide fa-3x"></i><span class="d-block">expand-wide</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-external-link fa-3x"></i><span class="d-block">external-link</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-external-link-alt fa-3x"></i><span class="d-block">external-link-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-external-link-square fa-3x"></i><span class="d-block">external-link-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-external-link-square-alt fa-3x"></i><span class="d-block">external-link-square-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-eye fa-3x"></i><span class="d-block">eye</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-eye-dropper fa-3x"></i><span class="d-block">eye-dropper</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-eye-slash fa-3x"></i><span class="d-block">eye-slash</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-fast-backward fa-3x"></i><span class="d-block">fast-backward</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-fast-forward fa-3x"></i><span class="d-block">fast-forward</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-fax fa-3x"></i><span class="d-block">fax</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-female fa-3x"></i><span class="d-block">female</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-fighter-jet fa-3x"></i><span class="d-block">fighter-jet</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file fa-3x"></i><span class="d-block">file</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-alt fa-3x"></i><span class="d-block">file-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-archive fa-3x"></i><span class="d-block">file-archive</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-audio fa-3x"></i><span class="d-block">file-audio</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-check fa-3x"></i><span class="d-block">file-check</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-code fa-3x"></i><span class="d-block">file-code</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-edit fa-3x"></i><span class="d-block">file-edit</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-excel fa-3x"></i><span class="d-block">file-excel</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-exclamation fa-3x"></i><span class="d-block">file-exclamation</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-image fa-3x"></i><span class="d-block">file-image</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-minus fa-3x"></i><span class="d-block">file-minus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-pdf fa-3x"></i><span class="d-block">file-pdf</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-plus fa-3x"></i><span class="d-block">file-plus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-powerpoint fa-3x"></i><span class="d-block">file-powerpoint</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-times fa-3x"></i><span class="d-block">file-times</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-video fa-3x"></i><span class="d-block">file-video</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-file-word fa-3x"></i><span class="d-block">file-word</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-film fa-3x"></i><span class="d-block">film</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-film-alt fa-3x"></i><span class="d-block">film-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-filter fa-3x"></i><span class="d-block">filter</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-fire fa-3x"></i><span class="d-block">fire</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-fire-extinguisher fa-3x"></i><span class="d-block">fire-extinguisher</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-flag fa-3x"></i><span class="d-block">flag</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-flag-checkered fa-3x"></i><span class="d-block">flag-checkered</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-flask fa-3x"></i><span class="d-block">flask</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-folder fa-3x"></i><span class="d-block">folder</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-folder-open fa-3x"></i><span class="d-block">folder-open</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-font fa-3x"></i><span class="d-block">font</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-forward fa-3x"></i><span class="d-block">forward</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-frown fa-3x"></i><span class="d-block">frown</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-futbol fa-3x"></i><span class="d-block">futbol</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-gamepad fa-3x"></i><span class="d-block">gamepad</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-gavel fa-3x"></i><span class="d-block">gavel</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-gem fa-3x"></i><span class="d-block">gem</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-genderless fa-3x"></i><span class="d-block">genderless</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-gift fa-3x"></i><span class="d-block">gift</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-glass-martini fa-3x"></i><span class="d-block">glass-martini</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-globe fa-3x"></i><span class="d-block">globe</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-graduation-cap fa-3x"></i><span class="d-block">graduation-cap</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-h-square fa-3x"></i><span class="d-block">h-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-h1 fa-3x"></i><span class="d-block">h1</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-h2 fa-3x"></i><span class="d-block">h2</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-h3 fa-3x"></i><span class="d-block">h3</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-lizard fa-3x"></i><span class="d-block">hand-lizard</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-paper fa-3x"></i><span class="d-block">hand-paper</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-peace fa-3x"></i><span class="d-block">hand-peace</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-point-down fa-3x"></i><span class="d-block">hand-point-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-point-left fa-3x"></i><span class="d-block">hand-point-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-point-right fa-3x"></i><span class="d-block">hand-point-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-point-up fa-3x"></i><span class="d-block">hand-point-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-pointer fa-3x"></i><span class="d-block">hand-pointer</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-rock fa-3x"></i><span class="d-block">hand-rock</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-scissors fa-3x"></i><span class="d-block">hand-scissors</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hand-spock fa-3x"></i><span class="d-block">hand-spock</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-handshake fa-3x"></i><span class="d-block">handshake</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hashtag fa-3x"></i><span class="d-block">hashtag</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hdd fa-3x"></i><span class="d-block">hdd</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-heading fa-3x"></i><span class="d-block">heading</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-headphones fa-3x"></i><span class="d-block">headphones</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-heart fa-3x"></i><span class="d-block">heart</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-heartbeat fa-3x"></i><span class="d-block">heartbeat</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hexagon fa-3x"></i><span class="d-block">hexagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-history fa-3x"></i><span class="d-block">history</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-home fa-3x"></i><span class="d-block">home</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hospital fa-3x"></i><span class="d-block">hospital</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hourglass fa-3x"></i><span class="d-block">hourglass</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hourglass-end fa-3x"></i><span class="d-block">hourglass-end</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hourglass-half fa-3x"></i><span class="d-block">hourglass-half</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-hourglass-start fa-3x"></i><span class="d-block">hourglass-start</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-i-cursor fa-3x"></i><span class="d-block">i-cursor</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-id-badge fa-3x"></i><span class="d-block">id-badge</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-id-card fa-3x"></i><span class="d-block">id-card</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-image fa-3x"></i><span class="d-block">image</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-images fa-3x"></i><span class="d-block">images</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-inbox fa-3x"></i><span class="d-block">inbox</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-inbox-in fa-3x"></i><span class="d-block">inbox-in</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-inbox-out fa-3x"></i><span class="d-block">inbox-out</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-indent fa-3x"></i><span class="d-block">indent</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-industry fa-3x"></i><span class="d-block">industry</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-industry-alt fa-3x"></i><span class="d-block">industry-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-info fa-3x"></i><span class="d-block">info</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-info-circle fa-3x"></i><span class="d-block">info-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-info-square fa-3x"></i><span class="d-block">info-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-italic fa-3x"></i><span class="d-block">italic</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-jack-o-lantern fa-3x"></i><span class="d-block">jack-o-lantern</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-key fa-3x"></i><span class="d-block">key</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-keyboard fa-3x"></i><span class="d-block">keyboard</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-language fa-3x"></i><span class="d-block">language</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-laptop fa-3x"></i><span class="d-block">laptop</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-leaf fa-3x"></i><span class="d-block">leaf</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-lemon fa-3x"></i><span class="d-block">lemon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-level-down fa-3x"></i><span class="d-block">level-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-level-down-alt fa-3x"></i><span class="d-block">level-down-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-level-up fa-3x"></i><span class="d-block">level-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-level-up-alt fa-3x"></i><span class="d-block">level-up-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-life-ring fa-3x"></i><span class="d-block">life-ring</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-lightbulb fa-3x"></i><span class="d-block">lightbulb</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-link fa-3x"></i><span class="d-block">link</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-lira-sign fa-3x"></i><span class="d-block">lira-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-list fa-3x"></i><span class="d-block">list</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-list-alt fa-3x"></i><span class="d-block">list-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-list-ol fa-3x"></i><span class="d-block">list-ol</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-list-ul fa-3x"></i><span class="d-block">list-ul</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-location-arrow fa-3x"></i><span class="d-block">location-arrow</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-lock fa-3x"></i><span class="d-block">lock</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-lock-alt fa-3x"></i><span class="d-block">lock-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-lock-open fa-3x"></i><span class="d-block">lock-open</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-lock-open-alt fa-3x"></i><span class="d-block">lock-open-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-alt-down fa-3x"></i><span class="d-block">long-arrow-alt-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-alt-left fa-3x"></i><span class="d-block">long-arrow-alt-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-alt-right fa-3x"></i><span class="d-block">long-arrow-alt-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-alt-up fa-3x"></i><span class="d-block">long-arrow-alt-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-down fa-3x"></i><span class="d-block">long-arrow-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-left fa-3x"></i><span class="d-block">long-arrow-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-right fa-3x"></i><span class="d-block">long-arrow-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-long-arrow-up fa-3x"></i><span class="d-block">long-arrow-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-low-vision fa-3x"></i><span class="d-block">low-vision</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-magic fa-3x"></i><span class="d-block">magic</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-magnet fa-3x"></i><span class="d-block">magnet</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-male fa-3x"></i><span class="d-block">male</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-map fa-3x"></i><span class="d-block">map</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-map-marker fa-3x"></i><span class="d-block">map-marker</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-map-marker-alt fa-3x"></i><span class="d-block">map-marker-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-map-pin fa-3x"></i><span class="d-block">map-pin</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-map-signs fa-3x"></i><span class="d-block">map-signs</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mars fa-3x"></i><span class="d-block">mars</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mars-double fa-3x"></i><span class="d-block">mars-double</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mars-stroke fa-3x"></i><span class="d-block">mars-stroke</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mars-stroke-h fa-3x"></i><span class="d-block">mars-stroke-h</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mars-stroke-v fa-3x"></i><span class="d-block">mars-stroke-v</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-medkit fa-3x"></i><span class="d-block">medkit</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-meh fa-3x"></i><span class="d-block">meh</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mercury fa-3x"></i><span class="d-block">mercury</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-microchip fa-3x"></i><span class="d-block">microchip</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-microphone fa-3x"></i><span class="d-block">microphone</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-microphone-alt fa-3x"></i><span class="d-block">microphone-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-microphone-slash fa-3x"></i><span class="d-block">microphone-slash</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-minus fa-3x"></i><span class="d-block">minus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-minus-circle fa-3x"></i><span class="d-block">minus-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-minus-hexagon fa-3x"></i><span class="d-block">minus-hexagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-minus-octagon fa-3x"></i><span class="d-block">minus-octagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-minus-square fa-3x"></i><span class="d-block">minus-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mobile fa-3x"></i><span class="d-block">mobile</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mobile-alt fa-3x"></i><span class="d-block">mobile-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mobile-android fa-3x"></i><span class="d-block">mobile-android</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mobile-android-alt fa-3x"></i><span class="d-block">mobile-android-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-money-bill fa-3x"></i><span class="d-block">money-bill</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-money-bill-alt fa-3x"></i><span class="d-block">money-bill-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-moon fa-3x"></i><span class="d-block">moon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-motorcycle fa-3x"></i><span class="d-block">motorcycle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-mouse-pointer fa-3x"></i><span class="d-block">mouse-pointer</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-music fa-3x"></i><span class="d-block">music</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-neuter fa-3x"></i><span class="d-block">neuter</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-newspaper fa-3x"></i><span class="d-block">newspaper</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-object-group fa-3x"></i><span class="d-block">object-group</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-object-ungroup fa-3x"></i><span class="d-block">object-ungroup</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-octagon fa-3x"></i><span class="d-block">octagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-outdent fa-3x"></i><span class="d-block">outdent</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-paint-brush fa-3x"></i><span class="d-block">paint-brush</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-paper-plane fa-3x"></i><span class="d-block">paper-plane</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-paperclip fa-3x"></i><span class="d-block">paperclip</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-paragraph fa-3x"></i><span class="d-block">paragraph</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-paste fa-3x"></i><span class="d-block">paste</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pause fa-3x"></i><span class="d-block">pause</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pause-circle fa-3x"></i><span class="d-block">pause-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-paw fa-3x"></i><span class="d-block">paw</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pen fa-3x"></i><span class="d-block">pen</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pen-alt fa-3x"></i><span class="d-block">pen-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pen-square fa-3x"></i><span class="d-block">pen-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pencil fa-3x"></i><span class="d-block">pencil</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pencil-alt fa-3x"></i><span class="d-block">pencil-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-percent fa-3x"></i><span class="d-block">percent</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-phone fa-3x"></i><span class="d-block">phone</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-phone-slash fa-3x"></i><span class="d-block">phone-slash</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-phone-square fa-3x"></i><span class="d-block">phone-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-phone-volume fa-3x"></i><span class="d-block">phone-volume</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plane fa-3x"></i><span class="d-block">plane</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plane-alt fa-3x"></i><span class="d-block">plane-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-play fa-3x"></i><span class="d-block">play</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-play-circle fa-3x"></i><span class="d-block">play-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plug fa-3x"></i><span class="d-block">plug</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plus fa-3x"></i><span class="d-block">plus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plus-circle fa-3x"></i><span class="d-block">plus-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plus-hexagon fa-3x"></i><span class="d-block">plus-hexagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plus-octagon fa-3x"></i><span class="d-block">plus-octagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-plus-square fa-3x"></i><span class="d-block">plus-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-podcast fa-3x"></i><span class="d-block">podcast</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-poo fa-3x"></i><span class="d-block">poo</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-portrait fa-3x"></i><span class="d-block">portrait</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-pound-sign fa-3x"></i><span class="d-block">pound-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-power-off fa-3x"></i><span class="d-block">power-off</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-print fa-3x"></i><span class="d-block">print</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-puzzle-piece fa-3x"></i><span class="d-block">puzzle-piece</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-qrcode fa-3x"></i><span class="d-block">qrcode</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-question fa-3x"></i><span class="d-block">question</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-question-circle fa-3x"></i><span class="d-block">question-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-question-square fa-3x"></i><span class="d-block">question-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-quote-left fa-3x"></i><span class="d-block">quote-left</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-quote-right fa-3x"></i><span class="d-block">quote-right</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-random fa-3x"></i><span class="d-block">random</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-rectangle-landscape fa-3x"></i><span class="d-block">rectangle-landscape</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-rectangle-portrait fa-3x"></i><span class="d-block">rectangle-portrait</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-rectangle-wide fa-3x"></i><span class="d-block">rectangle-wide</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-recycle fa-3x"></i><span class="d-block">recycle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-redo fa-3x"></i><span class="d-block">redo</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-redo-alt fa-3x"></i><span class="d-block">redo-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-registered fa-3x"></i><span class="d-block">registered</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-repeat fa-3x"></i><span class="d-block">repeat</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-repeat-1 fa-3x"></i><span class="d-block">repeat-1</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-repeat-1-alt fa-3x"></i><span class="d-block">repeat-1-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-repeat-alt fa-3x"></i><span class="d-block">repeat-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-reply fa-3x"></i><span class="d-block">reply</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-reply-all fa-3x"></i><span class="d-block">reply-all</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-retweet fa-3x"></i><span class="d-block">retweet</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-retweet-alt fa-3x"></i><span class="d-block">retweet-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-road fa-3x"></i><span class="d-block">road</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-rocket fa-3x"></i><span class="d-block">rocket</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-rss fa-3x"></i><span class="d-block">rss</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-rss-square fa-3x"></i><span class="d-block">rss-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ruble-sign fa-3x"></i><span class="d-block">ruble-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-rupee-sign fa-3x"></i><span class="d-block">rupee-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-save fa-3x"></i><span class="d-block">save</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-scrubber fa-3x"></i><span class="d-block">scrubber</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-search fa-3x"></i><span class="d-block">search</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-search-minus fa-3x"></i><span class="d-block">search-minus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-search-plus fa-3x"></i><span class="d-block">search-plus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-server fa-3x"></i><span class="d-block">server</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-share fa-3x"></i><span class="d-block">share</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-share-all fa-3x"></i><span class="d-block">share-all</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-share-alt fa-3x"></i><span class="d-block">share-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-share-alt-square fa-3x"></i><span class="d-block">share-alt-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-share-square fa-3x"></i><span class="d-block">share-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shekel-sign fa-3x"></i><span class="d-block">shekel-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shield fa-3x"></i><span class="d-block">shield</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shield-alt fa-3x"></i><span class="d-block">shield-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shield-check fa-3x"></i><span class="d-block">shield-check</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ship fa-3x"></i><span class="d-block">ship</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shopping-bag fa-3x"></i><span class="d-block">shopping-bag</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shopping-basket fa-3x"></i><span class="d-block">shopping-basket</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shopping-cart fa-3x"></i><span class="d-block">shopping-cart</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-shower fa-3x"></i><span class="d-block">shower</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sign-in fa-3x"></i><span class="d-block">sign-in</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sign-in-alt fa-3x"></i><span class="d-block">sign-in-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sign-language fa-3x"></i><span class="d-block">sign-language</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sign-out fa-3x"></i><span class="d-block">sign-out</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sign-out-alt fa-3x"></i><span class="d-block">sign-out-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-signal fa-3x"></i><span class="d-block">signal</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sitemap fa-3x"></i><span class="d-block">sitemap</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sliders-h fa-3x"></i><span class="d-block">sliders-h</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sliders-h-square fa-3x"></i><span class="d-block">sliders-h-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sliders-v fa-3x"></i><span class="d-block">sliders-v</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sliders-v-square fa-3x"></i><span class="d-block">sliders-v-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-smile fa-3x"></i><span class="d-block">smile</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-snowflake fa-3x"></i><span class="d-block">snowflake</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort fa-3x"></i><span class="d-block">sort</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-alpha-down fa-3x"></i><span class="d-block">sort-alpha-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-alpha-up fa-3x"></i><span class="d-block">sort-alpha-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-amount-down fa-3x"></i><span class="d-block">sort-amount-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-amount-up fa-3x"></i><span class="d-block">sort-amount-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-down fa-3x"></i><span class="d-block">sort-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-numeric-down fa-3x"></i><span class="d-block">sort-numeric-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-numeric-up fa-3x"></i><span class="d-block">sort-numeric-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sort-up fa-3x"></i><span class="d-block">sort-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-space-shuttle fa-3x"></i><span class="d-block">space-shuttle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-spade fa-3x"></i><span class="d-block">spade</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-spinner fa-3x"></i><span class="d-block">spinner</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-spinner-third fa-3x"></i><span class="d-block">spinner-third</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-square fa-3x"></i><span class="d-block">square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-star fa-3x"></i><span class="d-block">star</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-star-exclamation fa-3x"></i><span class="d-block">star-exclamation</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-star-half fa-3x"></i><span class="d-block">star-half</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-step-backward fa-3x"></i><span class="d-block">step-backward</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-step-forward fa-3x"></i><span class="d-block">step-forward</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-stethoscope fa-3x"></i><span class="d-block">stethoscope</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sticky-note fa-3x"></i><span class="d-block">sticky-note</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-stop fa-3x"></i><span class="d-block">stop</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-stop-circle fa-3x"></i><span class="d-block">stop-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-stopwatch fa-3x"></i><span class="d-block">stopwatch</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-street-view fa-3x"></i><span class="d-block">street-view</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-strikethrough fa-3x"></i><span class="d-block">strikethrough</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-subscript fa-3x"></i><span class="d-block">subscript</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-subway fa-3x"></i><span class="d-block">subway</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-suitcase fa-3x"></i><span class="d-block">suitcase</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sun fa-3x"></i><span class="d-block">sun</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-superscript fa-3x"></i><span class="d-block">superscript</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sync fa-3x"></i><span class="d-block">sync</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-sync-alt fa-3x"></i><span class="d-block">sync-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-table fa-3x"></i><span class="d-block">table</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tablet fa-3x"></i><span class="d-block">tablet</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tablet-alt fa-3x"></i><span class="d-block">tablet-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tablet-android fa-3x"></i><span class="d-block">tablet-android</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tablet-android-alt fa-3x"></i><span class="d-block">tablet-android-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tachometer fa-3x"></i><span class="d-block">tachometer</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tachometer-alt fa-3x"></i><span class="d-block">tachometer-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tag fa-3x"></i><span class="d-block">tag</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tags fa-3x"></i><span class="d-block">tags</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tasks fa-3x"></i><span class="d-block">tasks</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-taxi fa-3x"></i><span class="d-block">taxi</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-terminal fa-3x"></i><span class="d-block">terminal</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-text-height fa-3x"></i><span class="d-block">text-height</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-text-width fa-3x"></i><span class="d-block">text-width</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-th fa-3x"></i><span class="d-block">th</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-th-large fa-3x"></i><span class="d-block">th-large</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-th-list fa-3x"></i><span class="d-block">th-list</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thermometer-empty fa-3x"></i><span class="d-block">thermometer-empty</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thermometer-full fa-3x"></i><span class="d-block">thermometer-full</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thermometer-half fa-3x"></i><span class="d-block">thermometer-half</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thermometer-quarter fa-3x"></i><span class="d-block">thermometer-quarter</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thermometer-three-quarters fa-3x"></i><span class="d-block">thermometer-three-quarters</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thumbs-down fa-3x"></i><span class="d-block">thumbs-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thumbs-up fa-3x"></i><span class="d-block">thumbs-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-thumbtack fa-3x"></i><span class="d-block">thumbtack</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ticket fa-3x"></i><span class="d-block">ticket</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-ticket-alt fa-3x"></i><span class="d-block">ticket-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-times fa-3x"></i><span class="d-block">times</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-times-circle fa-3x"></i><span class="d-block">times-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-times-hexagon fa-3x"></i><span class="d-block">times-hexagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-times-octagon fa-3x"></i><span class="d-block">times-octagon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-times-square fa-3x"></i><span class="d-block">times-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tint fa-3x"></i><span class="d-block">tint</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-toggle-off fa-3x"></i><span class="d-block">toggle-off</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-toggle-on fa-3x"></i><span class="d-block">toggle-on</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-trademark fa-3x"></i><span class="d-block">trademark</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-train fa-3x"></i><span class="d-block">train</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-transgender fa-3x"></i><span class="d-block">transgender</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-transgender-alt fa-3x"></i><span class="d-block">transgender-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-trash fa-3x"></i><span class="d-block">trash</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-trash-alt fa-3x"></i><span class="d-block">trash-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tree fa-3x"></i><span class="d-block">tree</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tree-alt fa-3x"></i><span class="d-block">tree-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-triangle fa-3x"></i><span class="d-block">triangle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-trophy fa-3x"></i><span class="d-block">trophy</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-trophy-alt fa-3x"></i><span class="d-block">trophy-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-truck fa-3x"></i><span class="d-block">truck</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tty fa-3x"></i><span class="d-block">tty</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tv fa-3x"></i><span class="d-block">tv</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-tv-retro fa-3x"></i><span class="d-block">tv-retro</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-umbrella fa-3x"></i><span class="d-block">umbrella</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-underline fa-3x"></i><span class="d-block">underline</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-undo fa-3x"></i><span class="d-block">undo</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-undo-alt fa-3x"></i><span class="d-block">undo-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-universal-access fa-3x"></i><span class="d-block">universal-access</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-university fa-3x"></i><span class="d-block">university</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-unlink fa-3x"></i><span class="d-block">unlink</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-unlock fa-3x"></i><span class="d-block">unlock</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-unlock-alt fa-3x"></i><span class="d-block">unlock-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-upload fa-3x"></i><span class="d-block">upload</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-usd-circle fa-3x"></i><span class="d-block">usd-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-usd-square fa-3x"></i><span class="d-block">usd-square</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-user fa-3x"></i><span class="d-block">user</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-user-alt fa-3x"></i><span class="d-block">user-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-user-circle fa-3x"></i><span class="d-block">user-circle</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-user-md fa-3x"></i><span class="d-block">user-md</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-user-plus fa-3x"></i><span class="d-block">user-plus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-user-secret fa-3x"></i><span class="d-block">user-secret</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-user-times fa-3x"></i><span class="d-block">user-times</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-users fa-3x"></i><span class="d-block">users</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-utensil-fork fa-3x"></i><span class="d-block">utensil-fork</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-utensil-knife fa-3x"></i><span class="d-block">utensil-knife</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-utensil-spoon fa-3x"></i><span class="d-block">utensil-spoon</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-utensils fa-3x"></i><span class="d-block">utensils</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-utensils-alt fa-3x"></i><span class="d-block">utensils-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-venus fa-3x"></i><span class="d-block">venus</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-venus-double fa-3x"></i><span class="d-block">venus-double</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-venus-mars fa-3x"></i><span class="d-block">venus-mars</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-video fa-3x"></i><span class="d-block">video</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-volume-down fa-3x"></i><span class="d-block">volume-down</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-volume-mute fa-3x"></i><span class="d-block">volume-mute</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-volume-off fa-3x"></i><span class="d-block">volume-off</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-volume-up fa-3x"></i><span class="d-block">volume-up</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-watch fa-3x"></i><span class="d-block">watch</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-wheelchair fa-3x"></i><span class="d-block">wheelchair</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-wifi fa-3x"></i><span class="d-block">wifi</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-window fa-3x"></i><span class="d-block">window</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-window-alt fa-3x"></i><span class="d-block">window-alt</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-window-close fa-3x"></i><span class="d-block">window-close</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-window-maximize fa-3x"></i><span class="d-block">window-maximize</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-window-minimize fa-3x"></i><span class="d-block">window-minimize</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-window-restore fa-3x"></i><span class="d-block">window-restore</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-won-sign fa-3x"></i><span class="d-block">won-sign</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-wrench fa-3x"></i><span class="d-block">wrench</span></div>
<div class="icon-wrap text-center col-4 col-md-3 col-lg-2 mb-3"><i class="fal fa-yen-sign fa-3x"></i><span class="d-block">yen-sign</span></div>
							
						</div>

						</div><!-- .entry-content -->
						<?php if ( get_edit_post_link() ) : ?>
						<footer class="entry-footer">
							<?php
								edit_post_link(
									sprintf(
										wp_kses(
											/* translators: %s: Name of current post. Only visible to screen readers */
											__( 'Edit <span class="screen-reader-text">%s</span>', 'bootscores' ),
											array(
												'span' => array(
													'class' => array(),
												),
											)
										),
										get_the_title()
									),
									'<span class="edit-link">',
									'</span>'
								);
							?>
						</footer><!-- .entry-footer -->
						<?php endif; ?>
					</article><!-- #post-<?php the_ID(); ?> -->
				</main><!-- #main -->
			</div><!-- #primary -->
		</div><!-- .col -->
	</div><!-- .row -->

<?php
//get_sidebar();
get_footer();
